In [1]:
import torch
import os 
# set available GPU
os.environ["CUDA_VISIBLE_DEVICES"] = "6"

## 矩阵与张量

In [2]:
x = torch.tensor(
    [
        [1, 2, 3],
        [4, 5.0, 6],
        [7, 8, 9]
    ]
)
print(x.shape, x)

torch.Size([3, 3]) tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [6]:
y = torch.Tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(y.shape, y)

torch.Size([3, 3]) tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [7]:
print(x.dtype, y.dtype)

torch.int64 torch.float32


In [3]:
x = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ]
    ]
    
)
print(x.shape)

torch.Size([2, 3, 3])


In [9]:
x = torch.zeros(1, 2, 3, 1)
print(x)

tensor([[[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]]])


In [10]:
x = torch.ones(1, 2, 3, 1)
x = torch.rand(1, 2, 3, 1)
print(x)
x = torch.randn([1, 2, 3, 1], device="cuda:0", requires_grad=True)
print(x)

tensor([[[[0.2780],
          [0.4346],
          [0.2693]],

         [[0.0056],
          [0.2510],
          [0.8040]]]])
tensor([[[[-0.1007],
          [-0.6169],
          [-0.2226]],

         [[ 2.0239],
          [ 0.5620],
          [-0.0897]]]])


## 四则运算与矩阵乘法

In [8]:
x = torch.randn(2, 2, 2)
print('x', x)
y = torch.randn(2, 2)[::, None].expand(2, 2, 2)
print('y', y)
z = x + y
print('z', z)
a = x - y
print('a', a)
b = x * y
print('b', b)
c = x / y

x tensor([[[ 1.7883,  1.8412],
         [ 0.4796,  0.3216]],

        [[ 1.3055,  1.3130],
         [-0.1197,  0.1863]]])
y tensor([[[-1.7623, -0.3706],
         [-1.7623, -0.3706]],

        [[-1.8145,  0.4805],
         [-1.8145,  0.4805]]])
z tensor([[[ 0.0260,  1.4707],
         [-1.2827, -0.0489]],

        [[-0.5091,  1.7935],
         [-1.9342,  0.6668]]])
a tensor([[[ 3.5506,  2.2118],
         [ 2.2419,  0.6922]],

        [[ 3.1200,  0.8325],
         [ 1.6948, -0.2942]]])
b tensor([[[-3.1516, -0.6823],
         [-0.8452, -0.1192]],

        [[-2.3689,  0.6309],
         [ 0.2172,  0.0895]]])


In [9]:
l = torch.zeros(2, 3)
print(l + x)

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/yuliu/anaconda3/envs/AGI/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3561188/3335689457.py", line 2, in <module>
    print(l + x)
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuliu/anaconda3/envs/AGI/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/yuliu/anaconda3/envs/AGI/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1396, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/yuliu/anaconda3/envs/AGI/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return 

#### 矩阵乘法

In [10]:
x = torch.randn(2, 3)
y = torch.randn(4, 3)
print(y.T.shape)
z = x @ y.T  # ab bc -> ac
print(z.shape)

torch.Size([3, 4])
torch.Size([2, 4])


In [27]:
z1 = torch.matmul(x, y.T)
print(z == z1)

tensor([[True, True, True, True],
        [True, True, True, True]])


In [11]:
x = torch.randn(5, 2, 3)
y = torch.randn(5, 3, 4)
z = x @ y
print(z.shape)

torch.Size([5, 2, 4])


In [15]:
x = torch.randn(2, 5, 2, 3)
y = torch.randn(2, 5, 4, 3)
# z = x @ y.T
# z = x @ y.permute(0, 1, 3, 2)
# z = x @ y.transpose(2, 3)
z = x @ y.transpose(-1, -2)
print(z.shape)

torch.Size([2, 5, 2, 4])


In [16]:
z = torch.einsum('bcij,bckj->bcik', x, y)
print(z.shape)

torch.Size([2, 5, 2, 4])


## 自动微分

In [18]:
x = torch.randn(2, 3)
x.requires_grad_(True)
y = (x * 2).sum()
y.backward()
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [19]:
x = torch.randn([2, 3], requires_grad=True)
y = torch.randn([3, 4], requires_grad=True)
z = x @ y
l = z.sum()
l.backward()

In [20]:
print(x.grad)
print(y.grad)

tensor([[-0.4454,  1.1645, -0.1907],
        [-0.4454,  1.1645, -0.1907]])
tensor([[-2.5393, -2.5393, -2.5393, -2.5393],
        [ 0.4827,  0.4827,  0.4827,  0.4827],
        [ 1.6783,  1.6783,  1.6783,  1.6783]])


## 神经网络

In [21]:
import torch.nn as nn
import torch.optim as optim

model = nn.Linear(5, 2)

x = torch.randn(10, 5)
y_target = torch.randn(10, 2)
criterion = nn.MSELoss()  
optimizer = optim.SGD(model.parameters(), lr=0.1)  
  
for epoch in range(10):  
    optimizer.zero_grad()  
    y = model(x)
    loss = criterion(y, y_target)  
    loss.backward()  
    optimizer.step()
    print("loss: ", loss.item())

loss:  1.595448613166809
loss:  1.3521206378936768
loss:  1.1732923984527588
loss:  1.0404361486434937
loss:  0.940604567527771
loss:  0.8646981120109558
loss:  0.8062798380851746
loss:  0.7607654333114624
loss:  0.7248649597167969
loss:  0.6961988806724548


In [22]:
from torchvision.datasets import CIFAR10, MNIST
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
from tqdm import tqdm
import torch.nn as nn
from torch import optim


torch.manual_seed(0)

In [24]:
# Load dataset
# dataset_train = CIFAR10(root='./data', train=True, transform=ToTensor(), download=True)
# dataset_test = CIFAR10(root='./data', train=False, transform=ToTensor(), download=True)
dataset_train = MNIST(root='./data', train=True, transform=ToTensor(), download=True)
dataset_test = MNIST(root='./data', train=False, transform=ToTensor(), download=True)
dataloader_train = DataLoader(dataset_train, batch_size=32, shuffle=True)
dataloader_test = DataLoader(dataset_test, batch_size=32, shuffle=False)

for x, y in tqdm(dataloader_train):
    print(x.shape, y.shape)
    print(y)
    break

  0%|          | 0/1875 [00:00<?, ?it/s]

torch.Size([32, 1, 28, 28]) torch.Size([32])
tensor([2, 7, 3, 1, 6, 7, 1, 6, 6, 0, 3, 9, 7, 2, 9, 6, 4, 9, 9, 1, 8, 7, 5, 8,
        2, 5, 3, 8, 1, 6, 3, 2])


In [25]:
# Define model
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        # self.fc = nn.Linear(32 * 32 * 3, 10)
        self.fc = nn.Linear(28 * 28, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x
    
# Define training and testing loop
def train(model, dataloader):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    # training loop
    for epoch in range(5):
        for x, y in tqdm(dataloader):
            x, y = x.cuda(), y.cuda()
            optimizer.zero_grad()
            y_pred = model(x)
            loss = criterion(y_pred, y)
            loss.backward()
            optimizer.step()
        print("loss: ", loss.item())

def test(model, dataloader):
    acc = 0
    for x, y in tqdm(dataloader):
        x, y = x.cuda(), y.cuda()
        y_pred = model(x)
        acc += (y_pred.argmax(dim=1) == y).float().mean().item()
    print("acc: ", acc / len(dataloader))


In [26]:
model = MyModel().cuda()
train(model, dataloader_train)
test(model, dataloader_test)

100%|██████████| 1875/1875 [00:07<00:00, 264.21it/s]


loss:  0.3949453830718994


100%|██████████| 1875/1875 [00:05<00:00, 360.38it/s]


loss:  0.32440489530563354


100%|██████████| 1875/1875 [00:05<00:00, 362.23it/s]


loss:  0.3008139729499817


100%|██████████| 1875/1875 [00:05<00:00, 325.17it/s]


loss:  0.3084794580936432


100%|██████████| 1875/1875 [00:05<00:00, 360.88it/s]


loss:  0.23537926375865936


100%|██████████| 313/313 [00:00<00:00, 444.62it/s]

acc:  0.924620607028754


In [94]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = nn.Sequential(
            # nn.Linear(32 * 32 * 3, 64),
            nn.Linear(28 * 28, 64),
            nn.ReLU(),
            nn.Linear(64, 10),
        )

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x
    
model = MyModel().cuda()
train(model, dataloader_train)
test(model, dataloader_test)

100%|██████████| 1875/1875 [00:08<00:00, 208.86it/s]


loss:  0.18687574565410614


100%|██████████| 1875/1875 [00:07<00:00, 239.59it/s]


loss:  0.17335914075374603


100%|██████████| 1875/1875 [00:07<00:00, 244.08it/s]


loss:  0.07729557156562805


100%|██████████| 1875/1875 [00:06<00:00, 269.02it/s]


loss:  0.08850011974573135


100%|██████████| 1875/1875 [00:09<00:00, 198.03it/s]


loss:  0.00430353032425046


100%|██████████| 313/313 [00:01<00:00, 244.00it/s]

acc:  0.9719448881789138


In [98]:
# conv model
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv = nn.Sequential(
            # nn.Conv2d(3, 16, 3, padding=1),
            nn.Conv2d(1, 16, 3, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(16, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
        )
        self.fc = nn.Sequential(
            # nn.Linear(64 * 8 * 8, 64),
            nn.Linear(64 * 7 * 7, 64),
            nn.ReLU(),
            nn.Linear(64, 10),
        )

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

model = MyModel().cuda()
train(model, dataloader_train)
test(model, dataloader_test)

  0%|          | 0/1875 [00:00<?, ?it/s]

100%|██████████| 1875/1875 [00:14<00:00, 125.36it/s]


loss:  0.005114540457725525


100%|██████████| 1875/1875 [00:14<00:00, 132.33it/s]


loss:  0.0012219055788591504


100%|██████████| 1875/1875 [00:15<00:00, 124.06it/s]


loss:  0.0006020505679771304


100%|██████████| 1875/1875 [00:14<00:00, 131.96it/s]


loss:  0.0022100345231592655


100%|██████████| 1875/1875 [00:13<00:00, 137.89it/s]


loss:  8.376239566132426e-05


100%|██████████| 313/313 [00:01<00:00, 204.47it/s]

acc:  0.9896166134185304
